#!/bin/bash

set -ex

usage() {
    cat <<'___'
Usage: make_kernel kind destdir

Kind: rock

___
    exit 1
}
if test -z "$2" || ! test -d "$3" ; then usage; fi

kind="$1"
DEST="$2"

if test "$kind" = "rock" ; then
    DEFCONFIG=rock-pi-4-rk3399_defconfig
    DTB=rk3399-rock-pi-4.dtb
    ARCH=arm64
    CROSS_COMPILE=aarch64-linux-gnu-
fi

export ARCH CROSS_COMPILE

mirror() {
if ! test -d $1/.git ; then
    if test -d ../$1 ; then
        git clone -s ../$1 $1
    else
        git clone --depth=10 --branch $kind git@git.extern.smurf.noris.de:$1.git $1
    fi
fi
}

mirror kernel
cd kernel
git checkout $kind
make olddefconfig
if ! grep -qs mkdeb-pkg scripts/package/Makefile ; then
    cat >>scripts/package/Makefile << '___'
mkdeb-pkg: FORCE 
	$(CONFIG_SHELL) $(srctree)/scripts/package/mkdebian
___
fi
make mkdeb-pkg
REL=$(make kernelrelease)
VERS=$(dpkg-parsechangelog | sed -ne s/^Version: //p)
cd ..
if test -s $DEST/linux.version && test "$(cat $DEST/linux.version)" = "$VERS"  ; then
    echo Kernel already current.
else
    cd kernel
    # we could analyze "present" instead, but that's way more work
    make -j$(ls -1 /sys/devices/system/cpu | grep 'cpu[0-9]' | wc -l) bindeb-pkg
    cd ..
    mv linux-image-${REL}_${VERS]_arm64.deb $DEST/linux-image.deb
    mv linux-libc-dev-${REL}_${VERS]_arm64.deb $DEST/linux-libc-dev.deb
    mv linux-headers-${REL}_${VERS]_arm64.deb $DEST/linux-headers.deb
    echo $VERS > $DEST/linux.version
fi

