#!/bin/bash

set -ex

usage() {
    cat <<'___'
Usage: make_loader kind destdir

Kind: rock

___
    exit 1
}
if test -z "$2" || ! test -d "$3" ; then usage; fi

kind="$1"
DEST="$2"

if test "$kind" = "rock" ; then
    DEFCONFIG=rock-pi-4-rk3399_defconfig
    DTB=rk3399-rock-pi-4.dtb
    ARCH=arm64
    CROSS_COMPILE=aarch64-linux-gnu-
    CHIP="rk3399"
fi

mirror() {
if ! test -d $1/.git ; then
    if test -d ../$1 ; then
        git clone -s ../$1 $1
    else
        git clone git@git.extern.smurf.noris.de:$1.git $1
    fi
fi
}

mirror u-boot
cd u-boot
git checkout $kind
make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE all
cd ..


if test "$kind" = "rock" ; then
    mirror rkbin
    TOOLPATH=rkbin/tools
        
    $TOOLPATH/loaderimage --pack --uboot u-boot/u-boot-dtb.bin $DEST/uboot.img 0x200000 --size 1024 1

    tools/mkimage -n rk3399 -T rksd -d rkbin/bin/rk33/rk3399_ddr_800MHz_v1.20.bin $DEST/idbloader.img
    cat rkbin/bin/rk33/rk3399_miniloader_v1.19.bin >> $DEST/idbloader.img
    cp rkbin/bin/rk33/rk3399_loader_v1.12.112.bin $DEST/boot1.img  # for upload via rkdeveloptool

    cat >$DEST/trust.ini <<EOF
[VERSION]
MAJOR=1
MINOR=0
[BL30_OPTION]
SEC=0
[BL31_OPTION]
SEC=1
PATH=rkbin/bin/rk33/rk3399_bl31_v1.26.elf
ADDR=0x10000
[BL32_OPTION]
SEC=0
[BL33_OPTION]
SEC=0
[OUTPUT]
PATH=$DEST/trust.img
EOF

    $TOOLPATH/trust_merger --size 1024 1 $DEST/trust.ini
fi

